# Generated by Django 4.2 on 2024-02-14 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab3', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='birth_date',
        ),
    ]
